version: '3.1'
services:
  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: boucek-dev
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - './mongodb_data_container:/data/db'

volumes:
  mongodb_data_container:
